# **Umit Kilinc - 101232721**

In [ ]:
import array
L = list(range(10))
A = array.array("i", L)
A

In [ ]:
import numpy as np


In [ ]:
# integer array:
np.array([1.5, 1, 4, 2, 5, 3])


In [ ]:
np.array([1, 2, 3, 4], dtype="float32")

In [ ]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

In [ ]:
# If the above code is complicated, let's take a look at the following:
for i in [2, 4, 6]:
  print(np.array(range(i, i + 3)))

In [ ]:
np.zeros(10, dtype = int)

In [ ]:
np.ones((3, 5), dtype=float)

In [ ]:
np.full((3, 5), 3.14)

In [ ]:
np.arange(0, 20, 2)

In [ ]:
np.linspace(0, 1, 5)

In [ ]:
np.random.random((3, 3))

In [ ]:
np.random.normal(0, 1, (3,3))

In [ ]:
np.random.randint(0, 10, (3, 3))

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.empty(3)

array([1., 1., 1.])

In [17]:
import numpy as np
np.random.seed(0) # seed for reproductibility

x1 = np.random.randint(10, size = 6) # one dimensional array
x2 = np.random.randint(10, size = (3, 4)) # two dimensional array
x3 = np.random.randint(10, size = (3, 4, 5)) # three dimensional array

array([5, 0, 3, 3, 7, 9])

In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [20]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [16]:
np.zeros(10,dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [10]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [22]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [23]:
print("dtype: ", x3.dtype)

dtype:  int32


In [26]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")


itemsize:  4 bytes
nbytes:  240 bytes


In [27]:
x1


array([5, 0, 3, 3, 7, 9])

In [28]:
x1[0]

5

In [29]:
x1[4]

7

In [32]:
x1[-5]

0

In [33]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
x2[0,0]

3

In [36]:
x2[2,1]

6

In [37]:
x2[0,0] = 12


In [38]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [39]:
x1

array([5, 0, 3, 3, 7, 9])

In [43]:
#numpy arrays have a fixed type
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

In [44]:
# x[start:stop:step]
#default values: start = 0: stop = size: step = 1


In [45]:
x1[:5]

array([3, 0, 3, 3, 7])

In [46]:
x1[5:]

array([9])

In [47]:
x1[1::2]

array([0, 3, 9])

In [48]:
x1[::-1]

array([9, 7, 3, 3, 0, 3])

In [50]:
x1[5::-2]

array([9, 3, 0])

In [51]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [52]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [53]:
# all rows, every other column
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [54]:
#reversin rows (please try reversing colums yourself)
x2[::-1, ::]

array([[ 1,  6,  7,  7],
       [ 7,  6,  8,  8],
       [12,  5,  2,  4]])

In [55]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [57]:
#first column of x2
print(x2[:,0])

[12  7  1]


In [59]:
# first row of x2
print(x2[0,:])

[12  5  2  4]


In [61]:
# same as previous
print(x2[0])

[12  5  2  4]


In [62]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [63]:
x2_sub = x2[0:2, 0:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [64]:
#lets modify the subarray
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [65]:
# checking the original array
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [66]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [67]:
#reshaping of arrays


In [68]:
grid = np.arange(1,10)
print(grid)

[1 2 3 4 5 6 7 8 9]


In [69]:
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [70]:
x1[np.newaxis,:]

array([[3, 0, 3, 3, 7, 9]])

In [71]:
x1[:,np.newaxis]

array([[3],
       [0],
       [3],
       [3],
       [7],
       [9]])

In [76]:
#concatenation of arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
grid = np.array([[1,2,3], ])

In [77]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
# concatinate along the first axis
np.concatenate([grid, grid], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])