In [1]:
import numpy as np

In [2]:
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [3]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [5]:
# The alias of absolute is abs
np.abs(x)

array([2, 1, 0, 1, 2])

In [7]:
#Absolute value return the magnitude
x = ([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [8]:
#Trigonometric functions
theta = np.linspace(0, np.pi, 3)

In [9]:
print("theta(theta)    :", theta)
print("sin(theta)    :", np.sin(theta))
print("cos(theta)    :", np.cos(theta))
print("tan(theta)    :", np.tan(theta))

theta(theta)    : [0.         1.57079633 3.14159265]
sin(theta)    : [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)    : [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)    : [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
